### ISSUE TITLE
'portmidi.h' file not found

### ISSUE THREAD

**Issue by jonsie** [rakyll/portmidi#13]
I am running OS X 10.10.1.  I have installed portmidi v217 via homebrew, and I have verified that the header files are linked from /usr/local/Cellar/portmidi/217/include/ to /usr/local/include.

When I run "go get github.com/rakyll/portmidi" or "go install" it errors:

```
./portmidi.go:20:11: fatal error: 'portmidi.h' file not found
 #include <portmidi.h>
          ^
1 error generated.
```

I am brand new to Go -- really just want to use it for music.  Any idea how to get this working?  Thanks.

**Comment by rakyll** [comment]
Brew installs the header files as well, they should be under /usr/local/Cellar/portmidi/217/include.

Is there a possibility that your brew install failed? What is in /usr/local/Cellar/portmidi?

**Comment by chemicalfire** [comment]
I have the same issue, brew install those files but it is still throwing the error. I'm still looking for a solution, if I find one Ill post it.

**Comment by chemicalfire** [comment]
Turns out I needed the command line tools from xcode. Works now.

**Comment by lucianthorr** [comment]
Just in case anyone stumbles onto this thread and is running into the `portmidi.h not found` issue on a Apple Silicon Mac, you just have to change the CFLAGS/LDFLAGS because Homebrew installs to a different location.

In portmidi.go:
```
// #cgo CFLAGS:  -I/opt/homebrew/include
// #cgo LDFLAGS: -lportmidi -L/opt/homebrew/lib
```

or setup some aliases, for example: 
```
sudo ln -s /opt/homebrew/lib /usr/local/lib
sudo ln -s /opt/homebrew/lib/libportmidi.dylib /usr/local/lib/libportmidi.dylib
sudo ln -s /opt/homebrew/lib/libportmidi.2.dylib /usr/local/lib/libportmidi.2.dylib
sudo ln -s /opt/homebrew/lib/libportmidi.2.0.3.dylib /usr/local/lib/libportmidi.2.0.3.dylib
```
