### ISSUE TITLE
Event struct doesn't expose entire Message slice

### ISSUE THREAD

**Issue by murdinc** [rakyll/portmidi#18]
Hi, I hacked on a fork of this library to get Go talking to an older synth over Sysex. The changes I made are breaking, but I was interested in contributing if I can. Perhaps there is a non-breaking way of doing this, or a version of this can be included in a future release? 

The diff is here: https://github.com/rakyll/portmidi/compare/master...murdinc:master

As far as I can tell, only 3 bytes of the Message are available currently, but I needed the entire message. 

###### Current struct:

```
// Event represents a MIDI event.
type Event struct {
	Timestamp Timestamp
	Status    int64
	Data1     int64
	Data2     int64
}
```

###### The changes I made are modeled after the `PmEvent Struct` in the portmidi docs:

```
// Event represents a MIDI event.
type Event struct {
	Timestamp Timestamp
	Message   Message
}

// Message represents a 4 byte message
type Message []byte


func (m Message) Status() byte {
	status := m[0]
	return status
}

func (m Message) Data1() byte {
	data1 := m[1]
	return data1
}

func (m Message) Data2() byte {
	data2 := m[2]
	return data2
}
```

**Comment by rakyll** [comment]
We can break the APIs, that's fine. Could you like to open a PR? Btw, why not Message just a []byte rather than of type Message?

**Comment by murdinc** [comment]
I'd love to open a PR (welcome to my first contribution on github, btw). I made Message a type to attach the Status and Data methods, hoping it might make it less work to adapt changes on consumer. I am not using it myself, though.

**Comment by murdinc** [comment]
I just learned that I diverged before some other changes and stepped on your side of a conflict with WriteSysEx(). When I tested out the code that adiknoth contributed to that func, it err's with `encoding/hex: odd length hex string`. My test synth is a Yamaha TX7 that expects 163 bytes for a single voice sysex message, which must be why I went with mkb218's version originally.

**Comment by murdinc** [comment]
I should have looked closer at the last pull here. It's solution is makes the most sense to me now, and it doesn't break anything in the process. I'll be adapting my usage to those changes and closing these requests. I sincerely appreciate your code review and this library. Thank you!
