### ISSUE TITLE
Golang MIDI collaboration

### ISSUE THREAD

**Issue by metakeule** [rakyll/portmidi#34]
Hi Jaana,

I am writing to you, since you worked on MIDI and I wrote a rather complete library in the last weeks that should serve as a toolkit for creating MIDI based applications.

I would like to invite to help out, making it a common standard for MIDI with Go, by providing you insight and expertise.

I spend some effort to have a common API for live and SMF messages/events.
A second major priority was to make lots of mostly independent small packages to allow 
small devices to just use what they need.

The other top priority is to make the API stable as in: no breakage.

Anyway I created the github group "gomidi" and already invited you -
 would be glad to have you on board.

The core repo is:
https://github.com/gomidi/midi

and there are two simple applications

https://github.com/gomidi/midispy
and
https://github.com/gomidi/smfimage

making use of the core.

Where you could help out:

- naming, I want to nail down to get the API stable, see https://github.com/gomidi/midi/issues/3
- ideas for the best abstraction of PitchBend and KeySignature (they are working but
I am not sure, I covered all use cases and in the best way).
- obviously testing and more obscure applications I might not have thought of
- build higher level tools (quantization, what not) on top of it
- seemless integration with your portmidi lib?

I did not announce the library yet, since I first wanted to get some feedback from developers that delved into the MIDI standard.... ;-)

What do you think?

Looking forward to hear from you.

Cheers,
Benny
(github.com/metakeule)

**Comment by rakyll** [comment]
Hello, I have very limited time nowadays and probably it is better to ask others to see if they can help; @kisielk, @mattetti and @brettbuddin are a few on the top of my head.

**Comment by brettbuddin** [comment]
I am very interested in helping out.

**Comment by metakeule** [comment]
@brettbuddin I invited you to the gomidi organization and the corresponding Google group. If you'd like to help out, please have a look at the open issues: https://github.com/gomidi/midi/issues

Thanks and welcome on board!
